apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gitlab-backup-mirror
spec:
  schedule: '0 2 * * *'
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: gitlab-backup-mirror
              image: containeroo/gitlab-backup-mirror:1.1.0
              env:
                - name: GITLAB_MINIO_ACCESSKEY
                  valueFrom:
                    secretKeyRef:
                      key: accesskey
                      name: gitlab-minio-secret
                - name: GITLAB_MINIO_SECRETKEY
                  valueFrom:
                    secretKeyRef:
                      key: secretkey
                      name: gitlab-minio-secret
              envFrom:
                - secretRef:
                    name: gitlab-backup-mirror
          restartPolicy: Never
