apiVersion: v1
kind: Secret
metadata:
  name: gitlab-backup-mirror-secret
type: Opaque
stringData:
  GITLAB_MINIO_URL: https://gitlab-minio.example.com
  BACKUP_MINIO_URL: https://minio-backup.example.com
  BACKUP_MINIO_ACCESSKEY: abc
  BACKUP_MINIO_SECRETKEY: def
  GITLAB_BACKUP_RETENTION: 7d0h0m
